import { ReactNode, useState } from "react";
import Head from "next/head";
import {
  Box,
  Button,
  Menu,
  MenuItem,
  SxProps,
  Typography,
} from "@mui/material";
import MoreVertIcon from "@mui/icons-material/MoreVert";
import { useRouter } from "next/router";

interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
  const router = useRouter();
  const open = Boolean(anchorEl);
  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    setAnchorEl(event.currentTarget);
  };
  const handleClose = () => {
    setAnchorEl(null);
  };
  return (
    <>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={HeaderWrapper}>
        <Box onClick={() => router.push("/books")} sx={{ cursor: "pointer" }}>
          <Typography color="white">ITO University</Typography>
        </Box>
        <Box>
          <Button
            id="basic-button"
            aria-controls={open ? "basic-menu" : undefined}
            aria-haspopup="true"
            aria-expanded={open ? "true" : undefined}
            onClick={handleClick}
          >
            <MoreVertIcon sx={{ color: "white" }} />
          </Button>
          <Menu
            id="basic-menu"
            anchorEl={anchorEl}
            open={open}
            onClose={handleClose}
            MenuListProps={{
              "aria-labelledby": "basic-button",
            }}
          >
            <MenuItem onClick={handleClose}>My Bookmarks</MenuItem>
            <MenuItem onClick={handleClose}>Switch Role</MenuItem>
            <MenuItem onClick={() => router.push("/books/create")}>
              Create Books
            </MenuItem>
          </Menu>
        </Box>
      </Box>
      <Box>{children}</Box>
    </>
  );
};

export default Layout;

const HeaderWrapper: SxProps = {
  backgroundColor: "blue",
  padding: "16px",
  display: "flex",
  justifyContent: "space-between",
};
